# version: "3.8"

services:
  # ডাটাবেজ সার্ভিস
  postgres_db:
    image: postgres:15-alpine
    container_name: node_postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5455:5432" # আপনার লোকাল পিসির জন্য ৫৪৫৫, কিন্তু ভেতরের জন্য ৫৪৩২
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # আপনার নোড জেএস অ্যাপ সার্ভিস
  api_server:
    build: .
    container_name: node_api_server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      # 👇 এখানে ৫৪৩২ করা হয়েছে, যাতে ডকারের ভেতরে নোড অ্যাপটি ডাটাবেজকে খুঁজে পায়
      - DATABASE_URL=postgresql://myuser:mypassword@postgres_db:5432/mydatabase?schema=public
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres_db

volumes:
  postgres_data:
