version: "3.8"

services:
  # ডাটাবেজ সার্ভিস
  postgres_db:
    image: postgres:15-alpine
    container_name: node_postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5455:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- নতুন যোগ করা Redis সার্ভিস ---
  redis_cache:
    image: redis:alpine
    container_name: node_redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # ---- আপনার নোড জেএস অ্যাপ সার্ভিস ----
  api_server:
    build: .
    container_name: node_api_server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://myuser:mypassword@postgres_db:5432/mydatabase?schema=public
      # এখানে Redis হোস্ট হিসেবে সার্ভিসের নাম (redis_cache) ব্যবহার করবেন
      - REDIS_URL=redis://redis_cache:6379
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres_db
      - redis_cache

volumes:
  postgres_data:
  redis_data: # নতুন ভলিউম
